services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: 'postgresql'
    networks:
      - network
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./packages/database/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
        -c logging_collector=on
        -c log_directory=/etc/postgresql/log
        -c log_file_mode=0664
        -c log_filename='postgresql-%Y-%m-%d_%H:%M:%S.log'
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: 'snak_redis'
    networks:
      - network
    ports:
      - '127.0.0.1:6379:6379'
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:?REDIS_PASSWORD is required}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:?REDIS_PASSWORD is required}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  network:
    driver: bridge
