services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: 'postgresql'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./packages/database/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
        -c logging_collector=on
        -c log_directory=/etc/postgresql/log
        -c log_file_mode=0664
        -c log_filename='postgresql-%Y-%m-%d_%H:%M:%S.log'
    restart: unless-stopped


