name: postgresql

services:
  init-logs:
    image: alpine
    container_name: 'init-logs'
    volumes:
      - ./log:/etc/postgresql/log
    command: chmod 777 /etc/postgresql/log

  postgresql-test:
    image: pgvector/pgvector:pg17
    container_name: 'posgresql-test'
    shm_size: 128m
    ports:
      - 5454:5432
    env_file:
      - ../../.env
    volumes:
      - ./log:/etc/postgresql/log
    depends_on:
      - init-logs
    command: >
      postgres
        -c logging_collector=on 
        -c log_directory=/etc/postgresql/log 
        -c log_file_mode=0664 
        -c log_min_messages=debug 
        -c log_filename='postgresql-%Y-%m-%d_%H:%M:%S.log'
