name: Publish Docker Images

on:
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata (snak-api)
        id: meta-snak-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/snak-api
          tags: |
            type=raw,value=${{ inputs.release-tag }}

      - name: Build & push (snak-api)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-snak-api.outputs.tags }}
          labels: ${{ steps.meta-snak-api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
